---
- hosts: node1
  become: true
  tasks:
          - name: "install httpd"
            yum:
                    name: httpd
                    state: latest
            notify: restart httpd
          - name: "install ypbind"
            yum:
                    name:
                            - ypbind
                            - yp-tools
                    state: latest
            notify: restart nis  
  handlers:
          - name: restart httpd
            service:
                    name: httpd
                    state: restarted
          - name: restart nis
            service:
                    name: ypbind
                    state: restarted        
