---

- hosts: webservers
  vars:
          home: /home/nithin/test
          pictures_folder: /home/nithin/test/pictures
  tasks:
          - name: "create a test folder"
            file:
                    path: "{{home}}"
                    state: directory

          - name: "create a file in home dir"
            file:
                    path: "{{home}}/awesome.txt"
                    state: touch

          - name: "create a folder in home"
            file:
                    path: "{{pictures_folder}}"
                    state: directory
...
