---
- hosts: node2
  become: yes
  tasks:
          - name: "install packages"
            yum:
                    name: "{{item}}"
                    state : present
            with_items:
                    - git
                    - vim
                    - zsh
